# This workflow validates that all Java changes:
# * successfully compile
# * successfully pass unit tests
# * successfully package
#
# on Windows
# The self-hosted runner is in LogRhythm's VMWare cluster in the datacenter
#

name: Java Continuous Integration - Windows
on:
  push:
    branches:
      - master
    paths:
      - '**/pom.xml'
      - '**/*.java'
      - '**/*.proto'
  workflow_dispatch:

  # Also trigger on pull requests when possible.
  # current blockers are primarily runtime. The logic to restrict execution to only modified mvn modules
  # doesn't work as-is on Windows
#  pull_request:
#    paths:
#      - '**/pom.xml'
#      - '**/*.java'
#      - '**/*.proto'

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Hi!"
