name: Test
on:
  push:
    branches:
      - master
    paths:
      - '**/pom.xml'
      - '**/*.java'
      - '**/*.proto'
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Hi!"
