# This workflow validates that all Java changes:
# * successfully compile
# * successfully pass unit tests
# * successfully package
#
# on Windows
# The self-hosted runner is in LogRhythm's VMWare cluster in the datacenter
#

name: Test Again
on:
  push:
    branches:
      - master
    paths:
      - '**/pom.xml'
      - '**/*.java'
      - '**/*.proto'
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Hi!"
